# Generated by Django 6.0.6 on 2026-07-02 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='status',
            field=models.CharField(default='pending', max_length=20),
        ),
    ]
